services:
  whatsapp-bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      IS_DOCKER: "true"
      OLLAMA_MODEL: "ollama-translator"
      OLLAMA_BASEURL: "http://host.docker.internal:11434"
    volumes:
      - whatsapp-go:/data
volumes:
  whatsapp-go:
