services:
  whatsapp-bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      IS_DOCKER: "true"
      OLLAMA_MODEL: "ollama-translator"
      OLLAMA_BASEURL: "http://host.docker.internal:11434"
      OPENROUTER_BASEURL: ${OPENROUTER_BASEURL}
      OPENROUTER_MODEL: ${OPENROUTER_MODEL}
      OPENROUTER_APIKEY: ${OPENROUTER_APIKEY}
      OPENROUTER_IMAGE_MODEL: ${OPENROUTER_IMAGE_MODEL}
    volumes:
      - whatsapp-go:/data
volumes:
  whatsapp-go:
