// Code generated by "stringer -type Message -trimprefix Message"; DO NOT EDIT.

package constants

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageText-0]
	_ = x[MessageExtendedText-1]
	_ = x[MessageImage-2]
	_ = x[MessageVideo-3]
	_ = x[MessageDocument-4]
	_ = x[MessageAudio-5]
	_ = x[MessageLocation-6]
	_ = x[MessageContact-7]
	_ = x[MessagePoll-8]
	_ = x[MessageUnknown-9]
}

const _Message_name = "TextExtendedTextImageVideoDocumentAudioLocationContactPollUnknown"

var _Message_index = [...]uint8{0, 4, 16, 21, 26, 34, 39, 47, 54, 58, 65}

func (i Message) String() string {
	if i < 0 || i >= Message(len(_Message_index)-1) {
		return "Message(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Message_name[_Message_index[i]:_Message_index[i+1]]
}
